spring:
  application:
    name: currency-exchange

  devtools:
    livereload:
      port: 36601

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: port8001

  devtools:
    livereload:
      port: 36602

server:
  port: 8001

---
spring:
  config:
    activate:
      on-profile: port8002

  devtools:
    livereload:
      port: 36603

server:
  port: 8002
